### ISSUE TITLE
Get RS-232 port working

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dougg3/mac-rom-simm-programmer#4]
```
I haven't really tested the RS-232 port on the board yet. I should add RS-232 
capability to the bootloader and programmer firmware, and allow the programmer 
software to go out of "auto detect USB port" mode and into "manually specify a 
serial port" mode.

I consider this one a pretty low priority though. USB is ubiquitous these days.
```

Original issue reported on code.google.com by `d...@schmorgal.com` on 14 May 2012 at 3:25

**Comment by dougg3** [comment]
I've decided against implementing this. The BMOW and CayMac programmers don't even have the RS-232 port populated, so it would be a waste. Only my original programmers would support it, and only if the RS-232 parts were populated.
